import React from 'react';
import { Link, useParams } from 'react-router-dom';
import CustomerSidebar from '../components/CustomerSidebar';
import { useAuth } from '../context/AuthContext';
import { useRFQs } from '../context/RFQContext';
import './Quotes.css';

const money = (value) => `₹${Number(value).toLocaleString('en-IN')}`;

export default function QuoteDetail() {
  const { rfqId } = useParams();
  const { currentUser } = useAuth();
  const { getRFQById, acceptQuotation, rejectQuotation, cancelRFQ } = useRFQs();
  const rfq = getRFQById(rfqId);
  if (!rfq || rfq.userId !== currentUser?.id) return <main className="customer-page"><div className="container customer-panel"><h1>RFQ not found</h1><Link to="/quotes" className="text-link">Back to quotes</Link></div></main>;
  const canCancel = ['Draft', 'Submitted', 'Quotation Received'].includes(rfq.status);
  return <main className="customer-page"><div className="container customer-layout"><CustomerSidebar /><div className="customer-content"><header className="customer-page-header"><p className="section-label">Quotation request</p><h1>{rfq.id}</h1><p>{rfq.title}</p></header><section className="customer-panel rfq-summary"><div className="rfq-detail-heading"><span className={`rfq-status ${rfq.status.toLowerCase().replaceAll(' ', '-')}`}>{rfq.status}</span><span>Created {rfq.createdAt}</span></div><div className="rfq-summary-grid"><div><small>Required by</small><strong>{rfq.requiredBy}</strong></div><div><small>Delivery address</small><strong>{rfq.deliveryAddress}</strong></div><div><small>Notes</small><strong>{rfq.notes || 'No additional notes'}</strong></div></div>{canCancel && <button type="button" className="btn-outline" onClick={() => window.confirm('Cancel this quotation request?') && cancelRFQ(rfq.id)}>Cancel RFQ</button>}</section><section className="customer-panel"><h2>Requested Products</h2><div className="rfq-items">{rfq.items.map((item) => <div className="rfq-item" key={`${item.productId}-${item.vendorId}`}><div><strong>{item.productName}</strong><small>{item.vendorName}</small></div><span>{item.quantity} {item.unit}</span>{item.targetPrice ? <span>Target {money(item.targetPrice)} / {item.unit}</span> : <span>No target price</span>}</div>)}</div></section><section className="customer-panel"><h2>Supplier Quotations</h2>{rfq.quotations.length ? <div className="quotation-grid">{rfq.quotations.map((quote) => <article className="quotation-card" key={quote.id}><div className="quotation-top"><div><span className="rfq-number">{quote.id}</span><h3>{quote.vendorName}</h3></div><span className={`rfq-status ${quote.status.toLowerCase()}`}>{quote.status}</span></div><p className="quotation-date">Received {quote.createdAt} · Valid until {quote.validUntil}</p>{quote.items.map((item) => <div className="quotation-line" key={item.productId}><span>{item.productName} × {item.quantity}</span><strong>{money(item.price * item.quantity)}</strong></div>)}<div className="quotation-line"><span>Delivery charge</span><strong>{money(quote.deliveryCharge)}</strong></div><div className="quotation-total"><span>Total</span><strong>{money(quote.total)}</strong></div><p className="quotation-notes">{quote.notes}</p>{quote.status === 'Pending' && rfq.status !== 'Accepted' && <div className="quotation-actions"><button type="button" className="btn-primary" onClick={() => window.confirm('Accept this quotation?') && acceptQuotation(rfq.id, quote.id)}>Accept Quote</button><button type="button" className="btn-outline" onClick={() => rejectQuotation(rfq.id, quote.id)}>Reject Quote</button></div>}</article>)}</div> : <p className="quotes-waiting">Waiting for suppliers to respond.</p>}</section><Link to="/quotes" className="text-link">← Back to quotations</Link></div></div></main>;
}
