import React, { useMemo, useState } from 'react';
import { ExternalLink, Package, Plus, Minus, Settings2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import VendorSidebar from '../components/VendorSidebar';
import InventoryAdjustmentModal from '../components/InventoryAdjustmentModal';
import { categories } from '../data/products';
import { useVendorProducts } from '../context/VendorProductContext';
import './VendorInventory.css';

export default function VendorInventory() {
  const { products, lowStockThreshold, setLowStockThreshold, setProductThreshold, getProductHealth, addStock, removeStock, setStock, activity } = useVendorProducts();
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('all'); const [health, setHealth] = useState('all'); const [sort, setSort] = useState('name'); const [modal, setModal] = useState(null); const [threshold, setThreshold] = useState(lowStockThreshold);
  const filtered = useMemo(() => products.filter((p) => `${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()) && (category === 'all' || p.category === category) && (health === 'all' || getProductHealth(p) === health)).sort((a,b) => sort === 'stock' ? Number(a.stock)-Number(b.stock) : sort === 'stock-desc' ? Number(b.stock)-Number(a.stock) : String(a.name).localeCompare(String(b.name))), [products, query, category, health, sort, getProductHealth]);
  const counts = products.reduce((result, product) => { result[getProductHealth(product)] += 1; return result; }, { Healthy: 0, 'Low Stock': 0, 'Out of Stock': 0 });
  const commitThreshold = (event) => { const value = Number(event.target.value); setThreshold(value); if (Number.isFinite(value) && value >= 0) setLowStockThreshold(value); };
  const submitAdjustment = (amount, note) => { const fn = modal.mode === 'add' ? addStock : modal.mode === 'remove' ? removeStock : setStock; fn(modal.product.id, amount, note); };
  return <main className="vendor-inventory-page"><div className="container vendor-layout"><VendorSidebar /><div className="vendor-content">
    <header className="vendor-header"><div><p className="section-label">Stock control</p><h1>Inventory</h1><p>Keep marketplace availability accurate with one live stock source.</p></div><label className="threshold-editor"><Settings2 size={16} /> Low-stock threshold <input type="number" min="0" value={threshold} onChange={commitThreshold} /> units</label></header>
    <div className="inventory-summary">{[['Total products', products.length, 'all'], ['Healthy', counts.Healthy, 'healthy'], ['Low stock', counts['Low Stock'], 'low'], ['Out of stock', counts['Out of Stock'], 'out']].map(([label,value,key]) => <button type="button" className={`inventory-summary-card ${health === ({healthy:'Healthy',low:'Low Stock',out:'Out of Stock'}[key] || '') ? 'selected' : ''}`} onClick={() => setHealth(key === 'all' ? 'all' : {healthy:'Healthy',low:'Low Stock',out:'Out of Stock'}[key])} key={label}><Package size={18}/><strong>{value}</strong><span>{label}</span></button>)}</div>
    <section className="vendor-panel inventory-panel"><div className="inventory-filters"><input placeholder="Search inventory" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(c => <option key={c.id} value={c.name}>{c.name}</option>)}</select><select value={health} onChange={(e) => setHealth(e.target.value)}><option value="all">All stock health</option><option>Healthy</option><option>Low Stock</option><option>Out of Stock</option></select><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="name">Sort: name</option><option value="stock">Stock: low to high</option><option value="stock-desc">Stock: high to low</option></select></div>
      <div className="inventory-table"><div className="inventory-row inventory-heading"><span>Product</span><span>Category</span><span>Stock</span><span>Threshold</span><span>Health</span><span>Actions</span></div>{filtered.map(product => { const state = getProductHealth(product); return <div className="inventory-row" key={product.id}><div><strong>{product.name}</strong><small>{product.unit || 'units'} · {product.status}</small></div><span>{product.category}</span><strong>{product.stock || 0}</strong><input className="inventory-threshold" aria-label={`Low stock threshold for ${product.name}`} type="number" min="0" step="1" value={product.lowStockThreshold ?? lowStockThreshold} onChange={(event) => { const value = Number(event.target.value); if (Number.isInteger(value) && value >= 0) setProductThreshold(product.id, value); }} /><em className={`inventory-health ${state.toLowerCase().replaceAll(' ','-')}`}>{state}</em><div className="inventory-actions"><button title="Add stock" onClick={() => setModal({product,mode:'add'})}><Plus size={15}/></button><button title="Remove stock" onClick={() => setModal({product,mode:'remove'})}><Minus size={15}/></button><button title="Set exact stock" onClick={() => setModal({product,mode:'set'})}>Set</button><Link title="View public product" to={`/shop/${product.id}`}><ExternalLink size={15}/></Link></div></div>; })}</div>{!filtered.length && <p className="product-empty">No inventory matches these filters.</p>}</section>
    <section className="vendor-panel inventory-history"><div className="vendor-section-heading"><div><p className="section-label">Audit trail</p><h2>Recent activity</h2></div></div>{activity.length ? activity.slice(0,10).map(item => <div className="activity-row" key={item.id}><span><strong>{item.productName}</strong><small>{item.mode === 'set' ? 'Set stock' : item.mode === 'add' ? 'Added' : 'Removed'} {item.amount} · {item.note || 'No note'}</small></span><b>{item.before} → {item.after}</b><time>{new Date(item.createdAt).toLocaleString()}</time></div>) : <p className="product-empty">Stock adjustments will appear here.</p>}</section>
  </div></div>{modal && <InventoryAdjustmentModal product={modal.product} mode={modal.mode} onClose={() => setModal(null)} onSubmit={submitAdjustment}/>}</main>;
}
