import React from 'react';
import { ArrowRight, BarChart3, FileText, IndianRupee, Package, Plus, ShoppingBag, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import VendorSidebar from '../components/VendorSidebar';
import { useAuth } from '../context/AuthContext';
import { useVendor } from '../context/VendorContext';
import { useVendorProducts } from '../context/VendorProductContext';
import './VendorDashboard.css';

export default function VendorDashboard() {
  const { currentUser } = useAuth();
  const { vendorProfile: profile, vendorStats: stats, recentOrders: orders, recentRFQs: rfqs } = useVendor();
  const { products, getProductHealth } = useVendorProducts();
  const lowStockCount = products.filter((product) => getProductHealth(product) === 'Low Stock').length;
  return <main className="vendor-dashboard-page"><div className="container vendor-layout"><VendorSidebar /><div className="vendor-content">
    <header className="vendor-header"><div><p className="section-label">Vendor dashboard</p><h1>Good morning, {currentUser?.name || profile.ownerName}</h1><p>{profile.businessName} · Track your store performance and marketplace activity.</p></div><Link to="/vendor/products" className="btn-primary"><Package size={17} /> Manage Products</Link></header>
    <section className="vendor-profile-strip"><div className="vendor-avatar">{profile.businessName.slice(0, 1)}</div><div><h2>{profile.businessName} {profile.verified && <span className="vendor-verified">Verified</span>}</h2><p>{profile.ownerName} · {profile.location}</p></div><Link to="/vendor/profile" className="text-link">Edit profile <ArrowRight size={14} /></Link></section>
    <section className="vendor-metric-grid"><Metric label="Total revenue" value={`₹${stats.totalRevenue.toLocaleString('en-IN')}`} icon={IndianRupee} note={`↑ ${stats.revenueChange}%`} /><Metric label="Total orders" value={stats.totalOrders} icon={ShoppingBag} note={`↑ ${stats.ordersChange}%`} /><Metric label="Active products" value={stats.activeProducts} icon={Package} note={`${lowStockCount} low stock`} /><Metric label="Pending RFQs" value={stats.pendingRFQs} icon={BarChart3} note="Needs attention" /></section>
    <section className="vendor-panel vendor-revenue-panel"><div className="vendor-section-heading"><div><p className="section-label">Revenue overview</p><h2>Sales performance</h2></div><span className="vendor-chart-note">Last 6 months</span></div><div className="vendor-revenue-chart" aria-label="Revenue overview for January through June">{[['Jan', 38], ['Feb', 52], ['Mar', 46], ['Apr', 68], ['May', 74], ['Jun', 92]].map(([month, height]) => <div className="vendor-bar-column" key={month}><span style={{ height: `${height}%` }} /> <small>{month}</small></div>)}</div></section>
    <div className="vendor-panels"><section className="vendor-panel"><div className="vendor-section-heading"><div><p className="section-label">Sales</p><h2>Recent Orders</h2></div><Link to="/vendor/orders" className="text-link">View all <ArrowRight size={14} /></Link></div>{orders.map((order) => <div className="vendor-order-row" key={order.id}><div><strong>{order.id}</strong><small>{order.buyer} · {order.date}</small></div><strong>₹{order.total.toLocaleString('en-IN')}</strong><span className={`vendor-status ${order.status.toLowerCase()}`}>{order.status}</span></div>)}</section>
      <section className="vendor-panel"><div className="vendor-section-heading"><div><p className="section-label">Opportunity</p><h2>Recent RFQs</h2></div><Link to="/vendor/quotations" className="text-link">View all <ArrowRight size={14} /></Link></div>{rfqs.map((rfq) => <div className="vendor-rfq-row" key={rfq.id}><div><strong>{rfq.id}</strong><small>{rfq.buyer} · {rfq.product} · {rfq.quantity}</small></div><span>{rfq.due}</span><span className={`vendor-status ${rfq.status.toLowerCase().replaceAll(' ', '-')}`}>{rfq.status}</span><Link className="btn-outline" to="/vendor/quotations">Respond</Link></div>)}</section></div>
    <section className="vendor-panel"><div className="vendor-section-heading"><div><p className="section-label">Inventory</p><h2>Product health</h2></div><Link to="/vendor/inventory" className="text-link">Manage inventory <ArrowRight size={14} /></Link></div><div className="vendor-product-list">{products.map((product) => <div key={product.id}><span>{product.name}</span><small className={getProductHealth(product) === 'Out of Stock' ? 'out' : ''}>{getProductHealth(product)} · {product.stock || 0} {product.unit || 'units'}</small></div>)}</div></section>
    <section className="vendor-panel"><div className="vendor-section-heading"><div><p className="section-label">Shortcuts</p><h2>Quick actions</h2></div></div><div className="vendor-quick-actions">{[['/vendor/products/new', 'Add Product', Plus], ['/vendor/products', 'Manage Products', Package], ['/vendor/inventory', 'Manage Inventory', BarChart3], ['/vendor/orders', 'View Orders', ShoppingBag], ['/vendor/quotations', 'View Quotations', FileText]].map(([to, label, Icon]) => <Link to={to} className="vendor-quick-action" key={label}><Icon size={17} /><span>{label}</span><ArrowRight size={14} /></Link>)}</div></section>
    <section className="vendor-panel vendor-profile-card"><div className="vendor-section-heading"><div><p className="section-label">Business profile</p><h2>{profile.businessName}</h2></div><Link to="/vendor/profile" className="btn-outline">Edit Profile</Link></div><div className="vendor-profile-details"><span><strong>Owner</strong>{profile.ownerName}</span><span><strong>Location</strong>{profile.location}</span><span><strong>Phone</strong>{profile.phone}</span><span><strong>Email</strong>{profile.email}</span><span><strong>Status</strong><em>{profile.status}</em></span></div></section>
  </div></div></main>;
}
function Metric({ label, value, icon: Icon, note }) { return <div className="vendor-metric"><span><Icon size={19} /></span><div><strong>{value}</strong><small>{label}</small><em><TrendingUp size={12} /> {note}</em></div></div>; }
